---
all:
  vars:
    ansible_user: "{{ lookup('env', 'T7_SSH_USER') }}"
    ansible_ssh_private_key_file: "~/.ssh/{{ ansible_user }}.key"
    ansible_port: "{{ lookup('env', 'T7_SSH_PORT') }}"
    become: true

nginx:
  hosts:
    nginx-01.home.t7-lab.pl:
  vars:
    ssl_certificate_path: "/etc/nginx/ssl/fullchain.wildcard.home.t7-lab.pl.pem"
    ssl_certificate_key_path: "/etc/nginx/ssl/wildcard.home.t7-lab.pl.key"

    nginx_sites:
      - zabbix-01
      - t7-dashboard
      - pihole
      - k8s-dashboard
      - uptime-kuma

    # Test environment
    uptime_kuma_01_test_server_name: "uptime-kuma-gui.test.home.t7-lab.pl"
    uptime_kuma_01_test_proxy_pass: "http://uptime-kuma.test.home.t7-lab.pl:3001"

    # Global / Prod / MGMT environment

    zabbix_server_name: "zabbix-server-01-gui.home.t7-lab.pl"
    zabbix_server_01_proxy_pass: "http://zabbix-server-01.home.t7-lab.pl:80"

    pihole_01_server_name: "pihole-01-gui.home.t7-lab.pl"
    pihole_01_proxy_pass: "http://pihole-01.home.t7-lab.pl:8080/"

    pihole_02_server_name: "pihole-02-gui.home.t7-lab.pl"
    pihole_02_proxy_pass: "http://pihole-02.home.t7-lab.pl:8080/"

    t7_dashboard_server_name: "t7-dashboard.home.t7-lab.pl"

    k8s_dashboard_server_name: "k8s-dashboard-gui.home.t7-lab.pl"
    k8s_dashboard_proxy_pass: "http://k8s-dashboard.home.t7-lab.pl:80"

    uptime_kuma_01_server_name: "uptime-kuma-gui.home.t7-lab.pl"
    uptime_kuma_01_proxy_pass: "http://uptime-kuma.home.t7-lab.pl:3001"

    service_verification_services:
      - nginx
      - ssh
...
